# Site/SEO settings
email: aqwang@berkeley.edu
permalink: /:year/:month/:day/:title/
google_analytics: 

title: Anqi(Anchie) Wang's Website
description: |
  I am a second-year Statistics PhD student at UC Berkeley with a research interest in developing machine learning methods for biomedical discovery. 
  I believe in finding a good rhythm—whether it's in a complex dataset, a classic R&B track, or my favorite running route around the Bay.
url: "https://anqiwang02.github.io"
baseurl: ""
twitter_username: 
default_img: 

# Home page settings
home_img: /assets/img/profile_img.png

# Profile settings
name: 
profile_img: /assets/img/profile_img.png
profile: 
social:
  github: 

# Experiences (for About me page)
research_experience:
  - title: "Statistics PhD Student"
    organization: "UC Berkeley"
    period: "2024 – Present"
    description: "Research in machine learning methods for biomedical discovery."

teaching_experience:
  - title: "Graduate Student Instructor"
    organization: "UC Berkeley"
    period: "Spring 2026"
    description: "Stat 214 (Data Analysis and Machine Learning)" 

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
